server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapperLocations: classpath:mapper/test20210119/*.xml
  type-aliases-package: com.example.demo.entities



object:
  name: Object
  blogurl: blog.objectspace.cn



